//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecomunica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int idpersona { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public long dpi { get; set; }
        public string fecha_nacimiento { get; set; }
        public bool estado { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int idrole { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
